set(CTEST_BUILD_NAME "$ENV{SGEN}-hdf5")
set(CTEST_SITE "$ENV{COMPUTERNAME}")

set(VER "$ENV{HDF5_VER}")
set(CTEST_SOURCE_DIRECTORY "${CTEST_SCRIPT_DIRECTORY}/lib/src/CMake-hdf5-${VER}/hdf5-${VER}")
set(CTEST_BINARY_DIRECTORY "${CTEST_SCRIPT_DIRECTORY}/lib/build/hdf5-${VER}/${CONF_DIR}")

set(BUILD_OPTIONS
-C${CTEST_SOURCE_DIRECTORY}/config/cmake/cacheinit.cmake
-DCMAKE_INSTALL_PREFIX:PATH=${CTEST_SCRIPT_DIRECTORY}/lib/install/hdf5-${VER}/${CONF_DIR}
-DBUILD_TESTING:BOOL=OFF
-DHDF5_BUILD_TOOLS:BOOL=$ENV{BUILD_TOOLS}
-DBUILD_SHARED_LIBS:BOOL=ON
-DHDF5_PACKAGE_EXTLIBS:BOOL=ON
-DHDF5_ENABLE_Z_LIB_SUPPORT:BOOL=ON
-DHDF5_ENABLE_SZIP_SUPPORT:BOOL=ON
-DHDF5_BUILD_HL_LIB:BOOL=ON
-DHDF5_BUILD_CPP_LIB:BOOL=OFF
-DHDF5_BUILD_FORTRAN:BOOL=OFF
-DHDF5_BUILD_EXAMPLES:BOOL=OFF
-DHDF5_ALLOW_EXTERNAL_SUPPORT:STRING=TGZ
-DTGZPATH:PATH=${CTEST_SCRIPT_DIRECTORY}/lib/src/CMake-hdf5-${VER}
)

if("${CONF_DIR}" STREQUAL "debug")
  list(APPEND BUILD_OPTIONS "-DCMAKE_BUILD_TYPE:STRING=Debug")
elseif("${CONF_DIR}" STREQUAL "release")
  list(APPEND BUILD_OPTIONS "-DCMAKE_BUILD_TYPE:STRING=Release")
elseif("${CONF_DIR}" STREQUAL "relwithdebinfo")
  list(APPEND BUILD_OPTIONS "-DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo")
elseif("${CONF_DIR}" STREQUAL "minsizerel")
  list(APPEND BUILD_OPTIONS "-DCMAKE_BUILD_TYPE:STRING=MinSizeRel")
endif()

message(STATUS "CTEST_CONFIGURATION_TYPE=${CTEST_CONFIGURATION_TYPE}")
# if(CTEST_CONFIGURATION_TYPE)
#   list(APPEND BUILD_OPTIONS "-DCMAKE_BUILD_TYPE:STRING=${CTEST_CONFIGURATION_TYPE}")
# endif()

CTEST_START("Experimental")
CTEST_CONFIGURE(BUILD "${CTEST_BINARY_DIRECTORY}"
                OPTIONS "${BUILD_OPTIONS}")
CTEST_BUILD(BUILD "${CTEST_BINARY_DIRECTORY}")

# # for hdf we build PACKAGE target instead of INSTALL target
# # since the szip and zlib libraries cmake configurations
# # are created only during the packaging stage
# # see lib/install/hdf5-${VER}/${CONF_DIR}/cmake
# CTEST_BUILD(BUILD "${CTEST_BINARY_DIRECTORY}" FLAGS "-G ZIP" TARGET package)

# if (WIN32)
#   file(COPY "${CTEST_BINARY_DIRECTORY}/_CPack_Packages/win64/ZIP/HDF5-${VER}-win64/"
#     DESTINATION "${CTEST_SCRIPT_DIRECTORY}/lib/install/hdf5-${VER}/${CONF_DIR}")
# endif()

if("${CMAKE_SYSTEM_NAME}" STREQUAL "Linux")
  file(COPY "${CTEST_BINARY_DIRECTORY}/_CPack_Packages/Linux/TGZ/HDF5-${VER}-Linux/HDF_Group/HDF5/${VER}/"
    DESTINATION "${CTEST_SCRIPT_DIRECTORY}/lib/install/hdf5-${VER}/${CONF_DIR}")
endif()
