<Project DefaultTargets="iriclib-build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <Import Project="programs.prop" Condition="'$(CURL)'==''" />

  <Import Project="directories.prop" Condition="'$(TOP_DIR)'==''" />

  <PropertyGroup>
    <GENERATOR_NO_QUOTES>$([System.String]::Copy($(GENERATOR)).Replace('"','') )</GENERATOR_NO_QUOTES>
  </PropertyGroup>

  <!-- appveyor-iriclib-artifacts -->

  <Target Name="appveyor-iriclib-artifacts" DependsOnTargets="iriclib-git-build-release">
    <Copy SourceFiles="$(SRC_DIR)\iriclib-git\_build_release\INSTALL\include\iriclib_f.h"
          DestinationFiles="$(SRC_DIR)\iriclib-git\_artifacts\libs\iriclib_f.h"
    />
    <Copy SourceFiles="$(SRC_DIR)\iriclib-git\_build_release\INSTALL\lib\iriclib.lib"
          DestinationFiles="$(SRC_DIR)\iriclib-git\_artifacts\libs\iriclib_x64_ifort.lib"
    />
    <Exec Command="7z a libs.zip libs\."
          WorkingDirectory="$(SRC_DIR)\iriclib-git\_artifacts"
    />
  </Target>

  <!-- iriclib_v4 -->

  <Target Name="iriclib_v4-build">
    <RemoveDir Directories="$(INSTALL_DIR)\iriclib-$(IRICLIB_VER)" />
    <Exec Command="ctest -S iriclib_v4.cmake -DCONF_DIR:STRING=debug   -D%22CTEST_CMAKE_GENERATOR:STRING=$(GENERATOR_NO_QUOTES)%22 -C Debug   -VV -O $(LOG_DIR)\$(SGEN)-iriclib_v4-debug.log" />
    <Exec Command="ctest -S iriclib_v4.cmake -DCONF_DIR:STRING=release -D%22CTEST_CMAKE_GENERATOR:STRING=$(GENERATOR_NO_QUOTES)%22 -C Release -VV -O $(LOG_DIR)\$(SGEN)-iriclib_v4-release.log" />
  </Target>

  <!-- iriclib-git -->

  <Target Name="iriclib-git-build" DependsOnTargets="iriclib-git-build-debug;iriclib-git-build-release" />

  <Target Name="iriclib-git-build-debug" DependsOnTargets="iriclib-git-clone;hdf5-build-debug;poco-build-debug">
    <RemoveDir Directories="$(SRC_DIR)\iriclib-git\_build_debug" />
    <Exec Command="ctest -S iriclib-git.cmake -DCONF_DIR:STRING=debug -D%22CTEST_CMAKE_GENERATOR:STRING=$(GENERATOR_NO_QUOTES)%22 -C Debug -VV -O $(LOG_DIR)\$(SGEN)-iriclib-git-debug.log" />
  </Target>

  <Target Name="iriclib-git-build-release" DependsOnTargets="iriclib-git-clone;hdf5-build-release;poco-build-release">
    <RemoveDir Directories="$(SRC_DIR)\iriclib-git\_build_release" />
    <Exec Command="ctest -S iriclib-git.cmake -DCONF_DIR:STRING=release -D%22CTEST_CMAKE_GENERATOR:STRING=$(GENERATOR_NO_QUOTES)%22 -C Release -VV -O $(LOG_DIR)\$(SGEN)-iriclib-git-release.log" />
  </Target>

  <Target Name="iriclib-git-clone" Condition="!Exists('$(SRC_DIR)\iriclib-git')">
    <Message Text="Cloning https://github.com/i-RIC/iriclib.git" />
    <Exec Command="git clone https://github.com/i-RIC/iriclib.git lib/src/iriclib-git" />
  </Target>

  <!-- iriclib -->

  <Target Name="iriclib-build" DependsOnTargets="iriclib-build-debug;iriclib-build-release" />

  <Target Name="iriclib-build-debug" Inputs="iriclib.targets;iriclib.cmake;$(INSTALL_DIR)\hdf5-$(HDF5_VER)\lib\hdf5_D.lib;$(INSTALL_DIR)\poco-$(POCO_VER)\lib\PocoFoundationd.lib" Outputs="$(INSTALL_DIR)\iriclib-$(IRICLIB_VER)\lib\iriclibd.lib" DependsOnTargets="iriclib-src">
    <RemoveDir Directories="$(BUILD_DIR)\iriclib-$(IRICLIB_VER)\debug" />
    <Exec Command="ctest -S iriclib.cmake -DCONF_DIR:STRING=debug -D%22CTEST_CMAKE_GENERATOR:STRING=$(GENERATOR_NO_QUOTES)%22 -C Debug -VV -O $(LOG_DIR)\$(SGEN)-iriclib-debug.log" />
  </Target>

  <Target Name="iriclib-build-release" Inputs="iriclib.targets;iriclib.cmake;$(INSTALL_DIR)\hdf5-$(HDF5_VER)\lib\hdf5.lib;$(INSTALL_DIR)\poco-$(POCO_VER)\lib\PocoFoundation.lib" Outputs="$(INSTALL_DIR)\iriclib-$(IRICLIB_VER)\lib\iriclib.lib" DependsOnTargets="iriclib-src">
    <RemoveDir Directories="$(BUILD_DIR)\iriclib-$(IRICLIB_VER)\release" />
    <Exec Command="ctest -S iriclib.cmake -DCONF_DIR:STRING=release -D%22CTEST_CMAKE_GENERATOR:STRING=$(GENERATOR_NO_QUOTES)%22 -C Release -VV -O $(LOG_DIR)\$(SGEN)-iriclib-release.log" />
  </Target>

  <Target Name="iriclib-src" DependsOnTargets="iriclib-download" Condition="!Exists('$(SRC_DIR)\iriclib-$(IRICLIB_VER)')">
    <Exec Command="7z x $(DOWNLOADS_DIR)\iriclib-$(IRICLIB_VER).zip -o$(SRC_DIR)" />
    <Exec Command="ren $(SRC_DIR)\iriclib_v4-$(IRICLIB_VER) iriclib-$(IRICLIB_VER)" />
  </Target>

  <Target Name="iriclib-download" Condition="!Exists('$(DOWNLOADS_DIR)\iriclib-$(IRICLIB_VER).zip')">
    <MakeDir Directories="$(DOWNLOADS_DIR)" />
    <Message Text="Downloading iriclib-$(IRICLIB_VER).zip" />
    <Exec Command="$(CURL) https://github.com/i-RIC/iriclib_v4/archive/v$(IRICLIB_VER).zip" WorkingDirectory="$(DOWNLOADS_DIR)" />
    <Move SourceFiles="$(DOWNLOADS_DIR)\v$(IRICLIB_VER).zip" DestinationFiles="$(DOWNLOADS_DIR)\iriclib-$(IRICLIB_VER).zip" />
  </Target>

</Project>
