<Project DefaultTargets="udunits-build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <Import Project="programs.prop" Condition="'$(CURL)'==''" />

  <Import Project="directories.prop" Condition="'$(TOP_DIR)'==''" />

  <!-- @(udunits-build-debug-deps) -->
  <ItemGroup>
    <udunits-build-debug-deps Include="udunits-src"/>
    <udunits-build-debug-deps Include="expat-build-debug" Condition=" '$(UseDeps)' == 'Yes' " />
  </ItemGroup>

  <!-- @(udunits-build-release-deps) -->
  <ItemGroup>
    <udunits-build-release-deps Include="udunits-src"/>
    <udunits-build-release-deps Include="expat-build-release" Condition=" '$(UseDeps)' == 'Yes' " />
  </ItemGroup>

  <Target Name="udunits-clean" DependsOnTargets="expat-clean">
    <RemoveDir Directories="$(BUILD_DIR)\udunits-$(UDUNITS_VER)" />
    <RemoveDir Directories="$(SRC_DIR)\udunits-$(UDUNITS_VER)" />
    <Delete Files="$(DOWNLOADS_DIR)\udunits-$(UDUNITS_VER).zip" />
  </Target>

  <Target Name="udunits-build" DependsOnTargets="udunits-build-debug;udunits-build-release" />

  <Target Name="udunits-build-debug" Inputs="udunits.targets;udunits.cmake;$(INSTALL_DIR)\expat-$(EXPAT_VER)\debug\lib\expatd.lib" Outputs="$(INSTALL_DIR)\udunits-$(UDUNITS_VER)\debug\lib\udunits2.lib" DependsOnTargets="@(udunits-build-debug-deps)">
    <RemoveDir Directories="$(BUILD_DIR)\udunits-$(UDUNITS_VER)" />
    <RemoveDir Directories="$(INSTALL_DIR)\udunits-$(UDUNITS_VER)\debug" />
    <Exec Command="ctest -S udunits.cmake -DCONF_DIR:STRING=debug -DCTEST_CMAKE_GENERATOR:STRING=$(GENERATOR) -C Debug -VV -O $(LOG_DIR)\$(SGEN)-udunits-debug.log" />
  </Target>

  <Target Name="udunits-build-release" Inputs="udunits.targets;udunits.cmake;$(INSTALL_DIR)\expat-$(EXPAT_VER)\release\lib\expat.lib" Outputs="$(INSTALL_DIR)\udunits-$(UDUNITS_VER)\release\lib\udunits2.lib" DependsOnTargets="@(udunits-build-release-deps)">
    <RemoveDir Directories="$(BUILD_DIR)\udunits-$(UDUNITS_VER)" />
    <RemoveDir Directories="$(INSTALL_DIR)\udunits-$(UDUNITS_VER)\release" />
    <Exec Command="ctest -S udunits.cmake -DCONF_DIR:STRING=release -DCTEST_CMAKE_GENERATOR:STRING=$(GENERATOR) -C Release -VV -O $(LOG_DIR)\$(SGEN)-udunits-release.log" />
  </Target>

  <Target Name="udunits-src" DependsOnTargets="udunits-download" Condition="!Exists('$(SRC_DIR)\udunits-$(UDUNITS_VER)')">
    <Exec Command="7z x $(DOWNLOADS_DIR)\udunits-$(UDUNITS_VER).zip -o$(SRC_DIR)" />
  </Target>

  <Target Name="udunits-download" Condition="!Exists('$(DOWNLOADS_DIR)\udunits-$(UDUNITS_VER).zip')">
    <MakeDir Directories="$(DOWNLOADS_DIR)" />
    <Message Text="Downloading udunits-$(UDUNITS_VER).zip" />
    <Exec Command="$(CURL) https://downloads.unidata.ucar.edu/udunits/$(UDUNITS_VER)/udunits-$(UDUNITS_VER).zip" WorkingDirectory="$(DOWNLOADS_DIR)" />
  </Target>
</Project>
